/*
 * This source file was generated by the Gradle 'init' task
 */
package adventofcode;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    public Integer negativeModulus(Integer x) {
        // Implement this to make -4 mod 100 return 96:
        x = x % 100;
        if(x < 0) {
            x += 100;
        }
        return x;
    }

    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void modulusOperation() {
        assertEquals(4, 104%100, "104 mod 100 should be 4");
        assertEquals(4, 204%100, "204 mod 100 should be 4");
        assertEquals(-4, -4%100, "-4 mod 100 should be -4");
        assertEquals(96, negativeModulus(-4), "custom negative modulus of -4 should be 96");
    }
}
